M48
; DRILL file {KiCad 9.0.3} date 2025-09-19T12:26:31+1200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-19T12:26:31+12:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.200
%
G90
G05
T1
X144.06Y-75.63
T2
X145.3Y-69.55
T3
X148.71Y-76.18
X148.71Y-79.98
T4
X157.3Y-68.0
M30
